version: '3.9'

services:
  postgres:
    container_name: dswi6db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "dswi6user"
      POSTGRES_PASSWORD: "dswi6pass"
      POSTGRES_DB: "dswi6"